version: "3"

services:
  app:
    build: .
    ports:
      - 8091:8080
    environment:
      SERVER_PORT: '8080'
      STORAGE_MODE: 'mongo'
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'miniblogs'
  database:
    image: mongo:4.4
    ports:
      - 27017:27017
