version: "3"

services:
  app:
    build: .
    depends_on:
      - database
      - cache
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: '8080'
      STORAGE_MODE: 'mongo'
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'miniblogs'
      REDIS_URL: 'redis://cache:6379'
      APP_MODE: 'SERVER'
  worker:
    build: .
    depends_on:
      - database
      - cache
    environment:
      STORAGE_MODE: 'mongo'
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'miniblogs'
      REDIS_URL: 'redis://cache:6379'
      APP_MODE: 'WORKER'
  database:
    image: mongo:4.4
    ports:
      - 27017:27017
  cache:
    image: redis:6.2.6
    ports:
      - 6379:6379
